language: node_js

node_js:
  - 12

install:
  - git clone --depth=1 --branch=master https://github.com/statcounter/rrweb-snapshot.git
  - yarn

script:
  - xvfb-run --server-args="-screen 0 1920x1080x24" npm test
